async function createNuclearModule(moduleArg={}){var moduleRtn;var n=moduleArg,aa=import.meta.url,p="",ba;try{p=(new URL(".",aa)).href}catch{}ba=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};var q=console.error.bind(console),r,ca=!1,da,ea,v,A,B,C,D,E,fa,ha,ia,ja,ka=!1;
function na(){var b=F.buffer;v=new Int8Array(b);B=new Int16Array(b);A=new Uint8Array(b);C=new Uint16Array(b);D=new Int32Array(b);E=new Uint32Array(b);fa=new Float32Array(b);ha=new Float64Array(b);ia=new BigInt64Array(b);ja=new BigUint64Array(b)}function oa(b){n.onAbort?.(b);b="Aborted("+b+")";q(b);ca=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ea?.(b);throw b;}var G;
async function pa(b){if(!r)try{var a=await ba(b);return new Uint8Array(a)}catch{}if(b==G&&r)b=new Uint8Array(r);else throw"both async and sync fetching of the wasm failed";return b}async function qa(b,a){try{var c=await pa(b);return await WebAssembly.instantiate(c,a)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function ra(b){var a=G;if(!r)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return qa(a,b)}var sa=b=>{for(;0<b.length;)b.shift()(n)},ta=[],ua=[],va=()=>{var b=n.preRun.shift();ua.push(b)};class wa{constructor(b){this.C=b-24}}
var xa=0,ya=0,H=b=>{for(var a="";;){var c=A[b++];if(!c)return a;a+=String.fromCharCode(c)}},I={},J={},K={},N=class extends Error{constructor(b){super(b);this.name="BindingError"}},za=b=>{throw new N(b);};function Aa(b,a,c={}){var d=a.name;if(!b)throw new N(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(b)){if(c.fa)return;throw new N(`Cannot register type '${d}' twice`);}J[b]=a;delete K[b];I.hasOwnProperty(b)&&(a=I[b],delete I[b],a.forEach(e=>e()))}
function O(b,a,c={}){return Aa(b,a,c)}
var Ba=(b,a,c)=>{switch(a){case 1:return c?d=>v[d]:d=>A[d];case 2:return c?d=>B[d>>1]:d=>C[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>ia[d>>3]:d=>ja[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ca=b=>{throw new N(b.A.D.B.name+" instance already deleted");},Da=!1,Ea=()=>{},P=b=>{if(!globalThis.FinalizationRegistry)return P=a=>a,b;Da=new FinalizationRegistry(a=>{a=a.A;--a.count.value;0===a.count.value&&(a.F?a.I.N(a.F):a.D.B.N(a.C))});P=a=>{var c=a.A;
c.F&&Da.register(a,{A:c},a);return a};Ea=a=>{Da.unregister(a)};return P(b)},Fa=[];function Q(){}
var Ga=(b,a)=>Object.defineProperty(a,"name",{value:b}),Ha={},Ia=(b,a,c)=>{if(void 0===b[a].L){var d=b[a];b[a]=function(...e){if(!b[a].L.hasOwnProperty(e.length))throw new N(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].L})!`);return b[a].L[e.length].apply(this,e)};b[a].L=[];b[a].L[d.R]=d}},Ja=(b,a)=>{if(n.hasOwnProperty(b))throw new N(`Cannot register public name '${b}' twice`);n[b]=a;n[b].R=void 0},Ka=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=
b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function La(b,a,c,d,e,f,g,h){this.name=b;this.constructor=a;this.P=c;this.N=d;this.H=e;this.da=f;this.U=g;this.ca=h;this.ha=[]}var Ma=(b,a,c)=>{for(;a!==c;){if(!a.U)throw new N(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.U(b);a=a.H}return b},Na=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Oa(b,a){if(null===a){if(this.X)throw new N(`null is not a valid ${this.name}`);return 0}if(!a.A)throw new N(`Cannot pass "${Na(a)}" as a ${this.name}`);if(!a.A.C)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ma(a.A.C,a.A.D.B,this.B)}
function Pa(b,a){if(null===a){if(this.X)throw new N(`null is not a valid ${this.name}`);if(this.W){var c=this.ia();null!==b&&b.push(this.N,c);return c}return 0}if(!a||!a.A)throw new N(`Cannot pass "${Na(a)}" as a ${this.name}`);if(!a.A.C)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.V&&a.A.D.V)throw new N(`Cannot convert argument of type ${a.A.I?a.A.I.name:a.A.D.name} to parameter type ${this.name}`);c=Ma(a.A.C,a.A.D.B,this.B);if(this.W){if(void 0===a.A.F)throw new N("Passing raw pointer to smart pointer is illegal");
switch(this.ka){case 0:if(a.A.I===this)c=a.A.F;else throw new N(`Cannot convert argument of type ${a.A.I?a.A.I.name:a.A.D.name} to parameter type ${this.name}`);break;case 1:c=a.A.F;break;case 2:if(a.A.I===this)c=a.A.F;else{var d=a.clone();c=this.ja(c,Qa(()=>d["delete"]()));null!==b&&b.push(this.N,c)}break;default:throw new N("Unsupported sharing policy");}}return c}
function Ra(b,a){if(null===a){if(this.X)throw new N(`null is not a valid ${this.name}`);return 0}if(!a.A)throw new N(`Cannot pass "${Na(a)}" as a ${this.name}`);if(!a.A.C)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.A.D.V)throw new N(`Cannot convert argument of type ${a.A.D.name} to parameter type ${this.name}`);return Ma(a.A.C,a.A.D.B,this.B)}function R(b){return this.G(E[b>>2])}
var Sa=(b,a,c)=>{if(a===c)return b;if(void 0===c.H)return null;b=Sa(b,a,c.H);return null===b?null:c.ca(b)},Ta={},Va=(b,a)=>{if(void 0===a)throw new N("ptr should not be undefined");for(;b.H;)a=b.U(a),b=b.H;return Ta[a]},S=class extends Error{constructor(b){super(b);this.name="InternalError"}},T=(b,a)=>{if(!a.D||!a.C)throw new S("makeClassHandle requires ptr and ptrType");if(!!a.I!==!!a.F)throw new S("Both smartPtrType and smartPtr must be specified");a.count={value:1};return P(Object.create(b,{A:{value:a,
writable:!0}}))};function U(b,a,c,d,e,f,g,h,l,k,m){this.name=b;this.B=a;this.X=c;this.V=d;this.W=e;this.ga=f;this.ka=g;this.aa=h;this.ia=l;this.ja=k;this.N=m;e||void 0!==a.H?this.J=Pa:(this.J=d?Oa:Ra,this.K=null)}var Wa=(b,a)=>{if(!n.hasOwnProperty(b))throw new S("Replacing nonexistent public symbol");n[b]=a;n[b].R=void 0},Xa=[],V=(b,a)=>{b=H(b);var c;(c=Xa[a])||(Xa[a]=c=Ya.get(a));if("function"!=typeof c)throw new N(`unknown function pointer with signature ${b}: ${a}`);return c};
class Za extends Error{}
var ab=b=>{b=$a(b);var a=H(b);W(b);return a},bb=(b,a)=>{function c(f){e[f]||J[f]||(K[f]?K[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new Za(`${b}: `+d.map(ab).join([", "]));},X=(b,a,c)=>{function d(h){h=c(h);if(h.length!==b.length)throw new S("Mismatched type converter count");for(var l=0;l<b.length;++l)O(b[l],h[l])}b.forEach(h=>K[h]=a);var e=Array(a.length),f=[],g=0;for(let [h,l]of a.entries())J.hasOwnProperty(l)?e[h]=J[l]:(f.push(l),I.hasOwnProperty(l)||(I[l]=[]),I[l].push(()=>
{e[h]=J[l];++g;g===f.length&&d(e)}));0===f.length&&d(e)},cb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(E[a+4*d>>2]);return c},db=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function eb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].K)return!0;return!1}
function fb(b,a,c,d,e,f){var g=a.length;if(2>g)throw new N("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,l=eb(a);c=!a[0].$;var k=a[0],m=a[1];d=[b,za,d,e,db,k.G.bind(k),m?.J.bind(m)];for(e=2;e<g;++e)k=a[e],d.push(k.J.bind(k));if(!l)for(e=h?1:2;e<a.length;++e)null!==a[e].K&&d.push(a[e].K);l=eb(a);e=a.length-2;m=[];k=["fn"];h&&k.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),k.push(`arg${g}Wired`);m=m.join(",");k=k.join(",");m=`return function (${m}) {\n`;
l&&(m+="var destructors = [];\n");var z=l?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${z}, this);\n`);for(g=0;g<e;++g){var t=`toArg${g}Wire`;m+=`var arg${g}Wired = ${t}(${z}, arg${g});\n`;w.push(t)}m+=(c||f?"var rv = ":"")+`invoker(${k});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<a.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==a[g].K&&(m+=`${f}_dtor(${f});\n`,
w.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(w,m+"}\n"))(...d);return Ga(b,a)}
var gb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},hb=[],Y=[0,1,,1,null,1,!0,1,!1,1],ib=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,hb.push(b))},jb=b=>{if(!b)throw new N(`Cannot use deleted val. handle = ${b}`);return Y[b]},Qa=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=hb.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},kb={name:"emscripten::val",G:b=>{var a=jb(b);ib(b);return a},J:(b,a)=>Qa(a),M:R,K:null},lb=(b,a)=>{switch(a){case 4:return function(c){return this.G(fa[c>>
2])};case 8:return function(c){return this.G(ha[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},mb=Object.assign({optional:!0},kb),nb=globalThis.TextDecoder&&new TextDecoder,ob=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},pb=(b=0,a)=>{var c=A;a=ob(c,b,a,!0);if(16<a-b&&c.buffer&&nb)return nb.decode(c.subarray(b,a));for(var d="";b<a;){var e=c[b++];if(e&128){var f=c[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=c[b++]&63;e=224==
(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|c[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},qb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,rb=(b,a,c)=>{b>>=1;a=ob(C,b,a/2,c);if(16<a-b&&qb)return qb.decode(C.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(C[b]);return c},sb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)B[a>>
1]=b.charCodeAt(e),a+=2;B[a>>1]=0;return a-d},tb=b=>2*b.length,ub=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var f=E[b+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},vb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;D[a>>2]=f;a+=4;if(a+4>c)break}D[a>>2]=0;return a-d},wb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},xb=[],yb=b=>{var a=xb.length;xb.push(b);return a},zb=(b,a)=>
{for(var c=Array(b),d=0;d<b;++d){var e=d,f=E[a+4*d>>2],g=J[f];if(void 0===g)throw b=`${`parameter ${d}`} has unknown type ${ab(f)}`,new N(b);c[e]=g}return c},Ab=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(E[a>>2]=Qa(d));return b},Bb={},Cb=b=>{var a=Bb[b];return void 0===a?H(b):a};
(()=>{let b=Q.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Q&&c instanceof Q))return!1;var d=this.A.D.B,e=this.A.C;c.A=c.A;var f=c.A.D.B;for(c=c.A.C;d.H;)e=d.U(e),d=d.H;for(;f.H;)c=f.U(c),f=f.H;return d===f&&e===c},clone:function(){this.A.C||Ca(this);if(this.A.T)return this.A.count.value+=1,this;var c=P,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.A;c=c(e.call(d,f,{A:{value:{count:g.count,S:g.S,T:g.T,C:g.C,D:g.D,F:g.F,I:g.I}}}));c.A.count.value+=1;c.A.S=!1;return c},
["delete"](){this.A.C||Ca(this);if(this.A.S&&!this.A.T)throw new N("Object already scheduled for deletion");Ea(this);var c=this.A;--c.count.value;0===c.count.value&&(c.F?c.I.N(c.F):c.D.B.N(c.C));this.A.T||(this.A.F=void 0,this.A.C=void 0)},isDeleted:function(){return!this.A.C},deleteLater:function(){this.A.C||Ca(this);if(this.A.S&&!this.A.T)throw new N("Object already scheduled for deletion");Fa.push(this);this.A.S=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(U.prototype,{ea(b){this.aa&&(b=this.aa(b));return b},Z(b){this.N?.(b)},M:R,G:function(b){function a(){return this.W?T(this.B.P,{D:this.ga,C:c,I:this,F:b}):T(this.B.P,{D:this,C:b})}var c=this.ea(b);if(!c)return this.Z(b),null;var d=Va(this.B,c);if(void 0!==d){if(0===d.A.count.value)return d.A.C=c,d.A.F=b,d.clone();d=d.clone();this.Z(b);return d}d=this.B.da(c);d=Ha[d];if(!d)return a.call(this);d=this.V?d.ba:d.pointerType;var e=Sa(c,this.B,d.B);return null===e?a.call(this):this.W?T(d.B.P,
{D:d,C:e,I:this,F:b}):T(d.B.P,{D:d,C:e})}});n.printErr&&(q=n.printErr);n.wasmBinary&&(r=n.wasmBinary);if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();
var $a,Db,W,F,Ya,Eb={e:(b,a,c)=>{var d=new wa(b);E[d.C+16>>2]=0;E[d.C+4>>2]=a;E[d.C+8>>2]=c;xa=b;ya++;throw xa;},p:()=>oa(""),g:(b,a,c,d,e)=>{a=H(a);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}O(b,{name:a,G:f,J:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},M:Ba(a,c,!d),K:null})},j:(b,a,c,d)=>{a=H(a);O(b,{name:a,G:function(e){return!!e},J:function(e,f){return f?c:d},M:function(e){return this.G(A[e])},K:null})},i:(b,a,c,d,e,f,g,h,l,k,m,z,w)=>{m=H(m);f=V(e,f);h&&=V(g,
h);k&&=V(l,k);w=V(z,w);var t=Ka(m);Ja(t,function(){bb(`Cannot construct ${m} due to unbound types`,[d])});X([b,a,c],d?[d]:[],u=>{u=u[0];if(d){var x=u.B;var L=x.P}else L=Q.prototype;u=Ga(m,function(...la){if(Object.getPrototypeOf(this)!==ma)throw new N(`Use 'new' to construct ${m}`);if(void 0===y.O)throw new N(`${m} has no accessible constructor`);var Ua=y.O[la.length];if(void 0===Ua)throw new N(`Tried to invoke ctor of ${m} with invalid number of parameters (${la.length}) - expected (${Object.keys(y.O).toString()}) parameters instead!`);
return Ua.apply(this,la)});var ma=Object.create(L,{constructor:{value:u}});u.prototype=ma;var y=new La(m,u,ma,w,x,f,h,k);if(y.H){var M;(M=y.H).Y??(M.Y=[]);y.H.Y.push(y)}x=new U(m,y,!0,!1,!1);M=new U(m+"*",y,!1,!1,!1);L=new U(m+" const*",y,!1,!0,!1);Ha[b]={pointerType:M,ba:L};Wa(t,u);return[x,M,L]})},h:(b,a,c,d,e,f)=>{var g=cb(a,c);e=V(d,e);X([],[b],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.B.O&&(h.B.O=[]);if(void 0!==h.B.O[a-1])throw new N(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.B.O[a-1]=()=>{bb(`Cannot construct ${h.name} due to unbound types`,g)};X([],g,k=>{k.splice(1,0,null);h.B.O[a-1]=fb(l,k,null,e,f);return[]});return[]})},a:(b,a,c,d,e,f,g,h,l)=>{var k=cb(c,d);a=H(a);a=gb(a);f=V(e,f);X([],[b],m=>{function z(){bb(`Cannot call ${w} due to unbound types`,k)}m=m[0];var w=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);h&&m.B.ha.push(a);
var t=m.B.P,u=t[a];void 0===u||void 0===u.L&&u.className!==m.name&&u.R===c-2?(z.R=c-2,z.className=m.name,t[a]=z):(Ia(t,a,w),t[a].L[c-2]=z);X([],k,x=>{x=fb(w,x,m,f,g,l);void 0===t[a].L?(x.R=c-2,t[a]=x):t[a].L[c-2]=x;return[]});return[]})},r:b=>O(b,kb),f:(b,a,c)=>{a=H(a);O(b,{name:a,G:d=>d,J:(d,e)=>e,M:lb(a,c),K:null})},c:(b,a,c,d,e)=>{a=H(a);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}O(b,{name:a,G:f,J:(h,l)=>l,M:Ba(a,c,0!==d),K:null})},b:(b,a,c)=>{function d(f){return new e(v.buffer,E[f+
4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=H(c);O(b,{name:c,G:d,M:d},{fa:!0})},o:b=>{O(b,mb)},s:(b,a)=>{a=H(a);O(b,{name:a,G(c){var d=(d=c+4)?pb(d,E[c>>2]):"";W(c);return d},J(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new N("Cannot pass non-string to std::string");var g;if(f)for(e=g=0;e<d.length;++e){var h=
d.charCodeAt(e);127>=h?g++:2047>=h?g+=2:55296<=h&&57343>=h?(g+=4,++e):g+=3}else g=d.length;e=g;g=Db(4+e+1);h=g+4;E[g>>2]=e;if(f){if(f=h,h=e+1,e=A,0<h){h=f+h-1;for(var l=0;l<d.length;++l){var k=d.codePointAt(l);if(127>=k){if(f>=h)break;e[f++]=k}else if(2047>=k){if(f+1>=h)break;e[f++]=192|k>>6;e[f++]=128|k&63}else if(65535>=k){if(f+2>=h)break;e[f++]=224|k>>12;e[f++]=128|k>>6&63;e[f++]=128|k&63}else{if(f+3>=h)break;e[f++]=240|k>>18;e[f++]=128|k>>12&63;e[f++]=128|k>>6&63;e[f++]=128|k&63;l++}}e[f]=0}}else A.set(d,
h);null!==c&&c.push(W,g);return g},M:R,K(c){W(c)}})},d:(b,a,c)=>{c=H(c);if(2===a){var d=rb;var e=sb;var f=tb}else d=ub,e=vb,f=wb;O(b,{name:c,G:g=>{var h=d(g+4,E[g>>2]*a,!0);W(g);return h},J:(g,h)=>{if("string"!=typeof h)throw new N(`Cannot pass non-string to C++ string type ${c}`);var l=f(h),k=Db(4+l+a);E[k>>2]=l/a;e(h,k+4,l+a);null!==g&&g.push(W,k);return k},M:R,K(g){W(g)}})},k:(b,a)=>{a=H(a);O(b,{$:!0,name:a,G:()=>{},J:()=>{}})},n:(b,a,c)=>{var [d,...e]=zb(b,a);a=d.J.bind(d);var f=e.map(l=>l.M.bind(l));
b--;var g={toValue:jb};b=f.map((l,k)=>{var m=`argFromPtr${k}`;g[m]=l;return`${m}(args${k?"+"+8*k:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Cb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${b})`;d.$||(g.toReturnWire=a,g.emval_returnValue=Ab,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),
h))(...Object.values(g));h=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return yb(Ga(h,c))},m:(b,a,c,d,e)=>xb[b](a,c,d,e),l:b=>{var a=jb(b);db(a);ib(b)},q:b=>{var a=A.length;b>>>=0;if(536870912<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(536870912,65536*Math.ceil(Math.max(b,d)/65536))-F.buffer.byteLength+65535)/65536|0;try{F.grow(d);na();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}},Z;
Z=await (async function(){function b(c){c=Z=c.exports;$a=c.w;Db=c.x;W=c.y;F=c.t;Ya=c.v;na();return Z}var a={a:Eb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});G??=n.locateFile?n.locateFile?n.locateFile("nuclear_war_engine.wasm",p):p+"nuclear_war_engine.wasm":(new URL("nuclear_war_engine.wasm",import.meta.url)).href;return b((await ra(a)).instance)}());
(function(){function b(){n.calledRun=!0;if(!ca){ka=!0;Z.u();da?.(n);n.onRuntimeInitialized?.();if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var a=n.postRun.shift();ta.push(a)}sa(ta)}}if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)va();sa(ua);n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):b()})();ka?moduleRtn=n:moduleRtn=new Promise((b,a)=>{da=b;ea=a});
;return moduleRtn}export default createNuclearModule;
